---
# Common system configuration tasks

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  tags: [timezone]

- name: Update all packages
  apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
  register: apt_upgrade
  tags: [packages]

- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    state: present
  tags: [packages]

- name: Install Python 3.12 and pip
  apt:
    name:
      - python3.12
      - python3.12-venv
      - python3-pip
      - python3-setuptools
    state: present
  tags: [python]

- name: Set Python 3.12 as default python3
  alternatives:
    name: python3
    path: /usr/bin/python3.12
    link: /usr/bin/python3
  tags: [python]

# Note: Skipping pip upgrade to respect PEP 668 externally-managed-environment
# The pip version from apt (python3-pip) is sufficient for system use
# If newer pip is needed, use break_system_packages: true (not recommended)
# - name: Upgrade pip
#   pip:
#     name: pip
#     state: latest
#     executable: pip3
#     break_system_packages: true
#   tags: [python]

- name: Create gryt group
  group:
    name: "{{ gryt_group }}"
    state: present
  tags: [user]

- name: Create gryt user
  user:
    name: "{{ gryt_user }}"
    group: "{{ gryt_group }}"
    groups: []
    home: "{{ gryt_home }}"
    shell: /bin/bash
    create_home: true
    state: present
  tags: [user]

- name: Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  tags: [security, updates]

- name: Enable automatic updates
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
  tags: [security, updates]

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: [security, fail2ban]

- name: Ensure fail2ban is running
  systemd:
    name: fail2ban
    state: started
    enabled: true
  tags: [security, fail2ban]

- name: Reboot if required
  reboot:
    msg: "Reboot initiated by Ansible for system updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: apt_upgrade.changed and reboot_after_upgrade | default(false)
  tags: [reboot]
